//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_Rep.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SALES_REPEntities : DbContext
    {
        public SALES_REPEntities()
            : base("name=SALES_REPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<tblBrand> tblBrands { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblContact> tblContacts { get; set; }
        public virtual DbSet<tblincrementid> tblincrementids { get; set; }
        public virtual DbSet<MDCODE> MDCODEs { get; set; }
        public virtual DbSet<tblSupplierPayment> tblSupplierPayments { get; set; }
        public virtual DbSet<ROUTE_MAP> ROUTE_MAP { get; set; }
        public virtual DbSet<tblStockIn> tblStockIns { get; set; }
        public virtual DbSet<tblVendor> tblVendors { get; set; }
        public virtual DbSet<TRANSACTION> TRANSACTIONs { get; set; }
        public virtual DbSet<tblCart> tblCarts { get; set; }
        public virtual DbSet<tmpcart> tmpcarts { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<tblOurCompany> tblOurCompanies { get; set; }
        public virtual DbSet<tblSalesRep> tblSalesReps { get; set; }
        public virtual DbSet<PRIOIRTY> PRIOIRTies { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
    
        public virtual ObjectResult<string> Proc_INCREMENT_ID(string tYPE)
        {
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Proc_INCREMENT_ID", tYPEParameter);
        }
    
        public virtual ObjectResult<string> Proc_INCREMENT_ID_Update(string tYPE)
        {
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Proc_INCREMENT_ID_Update", tYPEParameter);
        }
    
        public virtual ObjectResult<PROC_SALESREP_OUTSTANDINGS_Result> PROC_SALESREP_OUTSTANDINGS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_SALESREP_OUTSTANDINGS_Result>("PROC_SALESREP_OUTSTANDINGS");
        }
    
        public virtual ObjectResult<string> PROC_INVOICE_LIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PROC_INVOICE_LIST");
        }
    }
}
