//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_Rep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int PId { get; set; }
        public string pcode { get; set; }
        public string barcode { get; set; }
        public string pdesc { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> ourprice { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> reorder { get; set; }
        public Nullable<decimal> LoyalityPrice { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string SinhalaDesc { get; set; }
        public int Brand_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public string Brand_Name { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
