//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_Rep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplierPayment
    {
        public int Id { get; set; }
        public string SupplierName { get; set; }
        public string ReferenceNo { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Account { get; set; }
        public string AccountNo { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<decimal> ChequeAmount { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> DueAmt { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public Nullable<decimal> PayingAmount { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
    }
}
